### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by swt2c** [vslavik/bakefile#109]
I hate to ask as I'm not volunteering to do it :-) but Linux distributions are starting to talk seriously about retiring Python 2.  I would mostly be interested in the legacy branch as that's still what wx uses.

**Comment by vslavik** [comment]
I have no plans to do that; especially not on the *legacy* branch (as its name very strongly suggests). Happy to merge patches, though.

**Comment by vadz** [comment]
We need to migrate wx build system to something else, we can't stay with legacy bakefile forever. As thing stand, I'm afraid we might end going back to dark ages and updating the different (luckily, much less numerous now...) make/project files manually as almost nothing is capable of generating Xcode projects anyhow. Or we can just give up to CMake :-(

In any case, I think that spending any effort on Python 3 support for the legacy branch is not worth it.

**Comment by Apteryks** [comment]
Has someone given it a try yet?  Being stuck on Python 2 means not being shipped in distributions such as GNU Guix and Debian, per policy.

**Comment by vadz** [comment]
Hi @Apteryks, this project has been more or less abandoned, unfortunately, so I'm afraid the only way to move forward with it would be to try doing it yourself. FWIW I don't think switching to Python 3 is trivial (i.e. I remember trying to do it many years ago and running into many problems), but it should be doable, of course, with enough motivation, and this would definitely be very welcome if we want to keep bakefile at all usable in the future.

**Comment by swt2c** [comment]
I also gave it a try a few years ago and gave up after determining that it wasn't worth the effort.  If I recall correctly, the biggest challenge was related to the C code that does string handling - one of the major changes between Python 2 and 3.
