### ISSUE TITLE
leading slash "/" removed from path names in includedirs and libdirs directories

### ISSUE THREAD

**Issue by john146** [vslavik/bakefile#122]
When I create a libdirs like the following:
libdirs = /usr/lib
              /usr/local/lib;

The GNUMakefile has the following:
-Lusr/lib -Lusr/local/lib. Since these are relative paths, not absolute paths, they don't work. Same for includedirs.

I'm using the following version:
pi@raspberrypi:~/projects/blue-box $ ../bakefile/bkl --version
bakefile 1.2.5.1-88

**Comment by vslavik** [comment]
`libdirs` is for paths within your project, i.e. for things that are portable. It's not for *system* paths that are non-portable and differ between toolsets *and* possibly individual machines.

Use `link-options` for this. But for `/usr/lib` (and probably `/usr/local/lib` as well) you don't need to specify anything for the GNU linker.
