### ISSUE TITLE
bakefile.org has an out-dated link to "legacy" 0.2 branch

### ISSUE THREAD

**Issue by davidcostanzo** [vslavik/bakefile#130]
The documentation on https://bakefile.org has a link to the legacy 0.2 branch, which is great because that's exactly what I need to build wxWidgets makefiles, according [a post on bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2018856).  After downloading it, building it, installing it, and running it to rebuild the wxWidgets makefiles, I discovered that I had downloaded the wrong 0.2 release.

The "legacy" link goes to 0.2.10 release.  The latest in the 0.2.X release is 0.2.12.1.  If the link had gone to:

   https://github.com/vslavik/bakefile/releases/tag/v0.2.12.1

It would have saved me a little bit of time.

**Comment by vadz** [comment]
Sorry, I've realized that I have no idea where does the text on https://bakefile.org/ come from and so don't know/can't update it. @vslavik do you still remember this by chance?

**Comment by vslavik** [comment]
The website is hosted at Netlify and was updated from a separate git repository. I imported that repository into the `website` branch here and changed deployment to use it. From now on, any changes made to the `website` branch will reflect on the website.

**Comment by vslavik** [comment]
Oh, and I fixed the link — thanks!
