### ISSUE TITLE
After building bakefile I still don't have bakefile_gen

### ISSUE THREAD

**Issue by sirus20x6** [vslavik/bakefile#132]
I built the parser, but I still don't seem to have any bakefile_gen needed by mysql++

**Comment by sirus20x6** [comment]
looks like I just needed legacy bakefile

**Comment by vslavik** [comment]
@sirus20x6 please read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html - nobody would have been able to help you with something as vague as your basically “it doesn’t work” anyway - and describing well would have made you realize the mistake *before* you created the issue.
