### ISSUE TITLE
No support to use a system provided antlr

### ISSUE THREAD

**Issue by Apteryks** [vslavik/bakefile#135]
Hello,

It seems the 3rdparty directory bundles a binary of antlr3, along its Python 2 bindings.  Is there a reason for this?  GNU Guix ships a `antlr3` package for example, and most GNU/Linux distributions have policies to have package use their provided libraries instead of bundling their own (GNU Guix does).

It'd make sense to test if antlr3 is available from the system before falling back to use the bundled copy, or allow configuring that behavior via a Make flag.  Also, is there any hope to see the project moving to a newer antlr release in the future?  antlr3 won't eternally be around.

Thank you.

**Comment by vslavik** [comment]
You're welcome to contribute patches.
