### ISSUE TITLE
BKL wrongly defines _USRDLL on VS studio project

### ISSUE THREAD

**Issue by mgruber4** [vslavik/bakefile#21]
The _USRDLL macro is related to ATL/MFC to control how a DLL is used/linked.

Because _USRDLL is implicitly defined it's not possible to build MFC extensions library which requires _AFXDLL. In this case compile errors are generated.

This is the documentation:

```
_AFXDLL             use shared MFC DLL
_AFXEXT             extension DLL version, implies _AFXDLL
_USRDLL             create regular DLL (_AFXDLL is valid too)
```

These are the occurrences of this macro:

```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\afx.h(173):// force inclusion of DLLMODUL.OBJ for _USRDLL
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\afx.h(174):#ifdef _USRDLL
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\afxdisp.h(501):#ifdef _USRDLL
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\afxdisp.h(505):#endif // _USRDLL
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\afxdisp.h(1195):#if defined(_USRDLL) && defined(_M_CEE)
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\afxver_.h(59)://  _USRDLL             create regular DLL (_AFXDLL is valid too)
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\atlbase.h(2817):#if !defined(_WINDLL) && !defined(_USRDLL)
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\atlbase.h(2818):  static_assert(!isDllModule, "'CAtlDllModuleT<T>' must be used with either _WINDLL or _USRDLL defined");
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\atlbase.h(2820):  static_assert(isDllModule, "'CAtlExeModuleT<T>' must be used with neither _WINDLL nor _USRDLL defined");
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\atlbase.h(4414):#ifdef _USRDLL
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\atlbase.h(4423):#ifdef _USRDLL
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\atlbase.h(4432):#ifdef _USRDLL
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\atlcom.h(2753):#if defined(_WINDLL) | defined(_USRDLL)
```

Currently I am overriding the problem adding the following code at the top of the stdafx.h file:

```
#if defined(_AFXDLL) & defined(_USRDLL)
#undef _USRDLL
#endif
```

**Comment by vadz** [comment]
Sorry, what do you mean? MSVS does whatever it does, but bkl doesn't define `_USRDLL` in the files it generates since a very long time and this is correct, I think.

**Comment by dcorbin-wintellect** [comment]
Generated this MFC .vcxproj with VS-2019 just today....
`
![image](https://user-images.githubusercontent.com/83300052/185631462-8eae7def-53d9-46ea-ac24-c0f8c46aecde.png)
`

**Comment by vadz** [comment]
Your project must be using one of the configurations for which MSVS predefines it. But what does this have to do with bkl? Do you actually _expect_ it to predefine it? Because this issue was about _not_ doing it, and it doesn't.

**Comment by dcorbin-wintellect** [comment]
> Your project must be using one of the configurations for which MSVS predefines it. But what does this have to do with bkl? Do you actually _expect_ it to predefine it? Because this issue was about _not_ doing it, and it doesn't.

Guess we are thinking about the word "completely" in different context. You are limiting to bkl, but since people searching the internet find things across the board (for example I am actually creating MFC application with CLR!!!!) the word can take on a universal context (i.e. Microsoft should totally drop all usage of _UXSRDLL as should all 2nd and 3rd party developers)

**Comment by vadz** [comment]
You're writing this in bkl bug tracker, surely the implicit context is that we are (well, were) speaking about the behaviour of bkl. Sorry, but I really don't understand your point.
