### ISSUE TITLE
Absolute includes

### ISSUE THREAD

**Issue by kirbyfan64** [vslavik/bakefile#52]
Right now, include directories cannot be absolute paths. This is bad when it comes to stuff like this:

```
library x {
    ...
    if ($(toolset) == gnu)
        includedirs += "`pkg-config --cflags freetype2`";
}
```

where I end up with a path like `../../source/usr/include/freetype2`; the source directory gets prepended to the pkg-config result. Putting a slash in front of the path doesn't work.

**Comment by vslavik** [comment]
Hardcoded absolute paths are intentionally not supported and they won’t be, for the simple reason that they make no sense whatsoever in portable (in the sense of “moving to any other computer than yours”) makefiles. Use a [make-time setting](http://docs.bakefile.org/en/latest/language.html#build-settings) for them instead.

That said, your example doesn’t even have anything to do with absolute paths. You are setting include *paths* variable to a value that is, after expansion, a list of C compiler *flags*, not paths (absolute or not). Observe how the `pkg-config` flags is called *cflags* and not *include-dirs*. So this really is just a case of GIGO, not a missing bkl feature.

Your very own issue #30 has a comment showing how to use `pkg-config` correctly, with `compiler-options`:

    compiler-options += "`pkg-config --cflags freetype2`";

**Comment by kirbyfan64** [comment]
*slaps self* I knew I had used this before but couldn't figure out what I did wrong...
