### ISSUE TITLE
VS 2015 support?

### ISSUE THREAD

**Issue by kirbyfan64** [vslavik/bakefile#55]
I'm toying with getting PEGTL to use Bakefile. Main issue: the only version of VS that it works on is 2015.

What's the chance of getting this supported?

**Comment by vadz** [comment]
I don't have VC14 yet, so I could be wrong but from what I know there haven't been any changes to the project/solution format, so adding a new `vs2015` toolset should be pretty trivial: just clone `VS2013{Solution,Project,Toolset}` in src/bkl/plugins/vs201x.py to `VS2015{Solution,Project,Toolset}` and replace `12` with `14`.
