### ISSUE TITLE
Bug in object filename in MSVC (VS2010)

### ISSUE THREAD

**Issue by rkg021083** [vslavik/bakefile#57]
Hi,
I have two files in the project having same name except the extension. Lets say foo.c and foo.cpp.

I declared global rule for vs2010 as following
vs2010.option.ClCompile.ObjectFileName = "\$(IntDir)%(Filename)%(Extension).obj"; 

I had put custom compilation rule for foo.c and output file was named foo.g.c (generated output)

Now when I open the vcproj file in text editor then ObjectFilename was listed as foo_.obj for foo.cpp

Rgds,
rkg

**Comment by vslavik** [comment]
Rename one of the files or put it into another directory… If you can't (hard to believe that, though), a PR fixing it would be welcome, but it's such a ridiculously rare situation that I'm unlikely to look into it myself, to be honest.

**Comment by rkg021083** [comment]
Hi vslavik,

I already found the solution other than what you have suggested. I just wanted to let the maintainer know about this. I would have fixed it in bakefile itself but amount of work needed is too big because I don't know abc of python and related technology.

Regards,
rkg
