### ISSUE TITLE
configure doesn't dectect my python 2.7.x series

### ISSUE THREAD

**Issue by aullidolunar** [vslavik/bakefile#58]
I'm using this old version because I like the generators. I trying to build from source using mingw + msys. I have python 2.7..and I'm using this line to compile:

$ PYTHON=c:/Python27/python.exe ./configure --prefix=c:/usr --disable-maintainer-mode

And I get this error:
checking whether C:/Python27/python.exe version >= 2.3.0... configure: error: too old

any ideas?

**Comment by kirbyfan64** [comment]
I'm guessing you're using the autoconf backend for legacy Bakefile? What project are you exactly trying to build.

**Comment by aullidolunar** [comment]
Hi @kirbyfan64 , I'm trying to build bakefile 0.2.9 in my windows box using my python interpreter.

**Comment by kirbyfan64** [comment]
Is there a particular reason you're using the legacy version?

**Comment by aullidolunar** [comment]
I haven't play much around the new version of bakefile, but taking from wxWidgets..I like to generate makefiles for nmake and mingw32-make utilities.

**Comment by kirbyfan64** [comment]
Ah, ok, that makes sense. Try this:

```bash
$ PYTHON=/c/Python27/python.exe ./configure --prefix=/c/usr --disable-maintainer-mode
```

**Comment by vadz** [comment]
Please look at `config.log` to see what was the exact reason for the failure, but I think @kirbyfan64 is right and you should use the MSYS path and not Windows path to it. Alternatively, don't set `PYTHON` at all and just set the `PATH` correctly.

Please reopen if this wasn't the case and you still think there is some problem with bakefile itself.
