### ISSUE TITLE
Object name truncated for source file with multiple extensions

### ISSUE THREAD

**Issue by ryan-phillips** [vslavik/bakefile#78]
When a source file name is converted to an object file name, up to two extensions are removed from the end of the file name. For example, *hello.x.c* is output to *hello.o* by the gnu toolset.

Furthermore, the checks for conflicting file names is performed before the second extension is removed, so bakefile will not recognize that *hello.x.c* and *hello.y.c* both compile to the same object.

**Comment by vslavik** [comment]
Closed in favour of #79. Please don’t create duplicate issues, one (the PR itself) is just fine.
