### ISSUE TITLE
Release (0.2.10): checkBakefileVersion bug. 

### ISSUE THREAD

**Issue by edorax** [vslavik/bakefile#92]
Version "0.2.10" is considered older than "0.2.2".

**Comment by vslavik** [comment]
Please do your homework before you file issues. Checking after-release commits (c1366ac94db897a1a2043fa18b13d62326c5d28c) or existing issues (#87) is not hard and would have avoided needless duplicates like this one.

**Comment by edorax** [comment]
Sorry for my poor knowledge to git/GitHub.

**Comment by vslavik** [comment]
Please stop spamming the tracker with useless comments (like your other pointlessly bugging one). This isn't about "poor knowledge" of GitHub: if you are capable of creating a new issue, you are perfectly capable of clicking the "Closed" link too.
