### ISSUE TITLE
Unknown python module called plugins

### ISSUE THREAD

**Issue by betrixed** [vslavik/bakefile#94]
bkl/"__init__.py"  is "import plugins".  
ModuleNotFoundError: No module named 'plugins'  
Any other dependencies?

**Comment by vslavik** [comment]
bkl uses Python 2, not 3.

**Comment by betrixed** [comment]
So change your readme to say so. 
I took literally python >= 2.6 to indicate also python >= 3.0  On my system all I had to do was change the first line in tool.py, when informed it was python 2 only, as below.
#!/usr/bin/python2

**Comment by vslavik** [comment]
Thanks for making a PR of your changes!
