### ISSUE TITLE
Please make a 0.2.11 release

### ISSUE THREAD

**Issue by swt2c** [vslavik/bakefile#95]
wx appears to be using 0.2.11 but 0.2.10 is the latest legacy release.

**Comment by TcT2k** [comment]
@vadz or @vslavik would be nice to have a release for this version to working on wxWidgets under windows.

**Comment by vadz** [comment]
I've created [the release](https://github.com/vslavik/bakefile/releases/tag/v0.2.11) and uploaded Windows binary, but I don't think I can do it under Mac (what is `productbuild` and what developer ID should I use?) and I don't even know how to make docs as I don't have fop under Linux, so I don't know if we can consider it to be really done or not.

**Comment by swt2c** [comment]
`productbuild` utility comes with macOS (or maybe Xcode).

For Developer ID, that's a special certificate that you get from Apple.  I'm guessing you probably don't have Václav's certificate, so he'll probably have to do that part.

**Comment by TcT2k** [comment]
I've installed and successfully used the windows release to update wxWidgets

**Comment by vslavik** [comment]
> but I don't think I can do it under Mac

Done, sorry for the delay.

**Comment by swt2c** [comment]
Thanks, do you mind also posting the tarball as well?

**Comment by vadz** [comment]
@swt2c My understanding is that Github-generated tarballs are just fine for bakefile.

**Comment by swt2c** [comment]
The only reason I asked was because Vaclav used to post a separate one before.  I didn't actually check the difference, but if the only difference is the autoconf files, then yeah, the github files are probably fine.

**Comment by vslavik** [comment]
There are some nontrivial requirements (SWIG, possibly Docbook toolchain) to bootstrap everything, so I uploaded the tarball too. Hopefully that'll *really* be the last 0.2 release...
